/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'court-navy': '#12213D',
        'court-navy-light': '#1C3159',
        'court-navy-lighter': '#294279',
        'amber': '#F2A93B',
        'amber-dark': '#D98F1F',
        'cream': '#F7F3E8',
        'hardwood': '#C98A4B',
        'win': '#2F9E44',
        'loss': '#E0523A',
        'ink': '#1A1A1A',
        app: 'var(--color-app-bg)',
        surface: 'var(--color-surface)',
        'surface-soft': 'var(--color-surface-soft)',
        sidebar: 'var(--color-sidebar)',
        'sidebar-active': 'var(--color-sidebar-active)',
        muted: 'var(--color-text-muted)',
        subtle: 'var(--color-text-subtle)',
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-soft': 'var(--color-primary-soft)',
        success: 'var(--color-success)',
        'success-soft': 'var(--color-success-soft)',
        warning: 'var(--color-warning)',
        'warning-soft': 'var(--color-warning-soft)',
        danger: 'var(--color-danger)',
        'danger-soft': 'var(--color-danger-soft)',
        info: 'var(--color-info)',
        'info-soft': 'var(--color-info-soft)',
        'score-bg': 'var(--color-score-bg)',
        'score-text': 'var(--color-score-text)',
        'score-accent': 'var(--color-score-accent)',
      },
      fontFamily: {
        display: ['Bahnschrift', 'Arial Narrow', 'sans-serif'],
        body: ['Segoe UI', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['Consolas', 'Courier New', 'monospace'],
        ui: ['Inter', 'ui-sans-serif', 'system-ui', 'Segoe UI', 'sans-serif'],
        sport: ['Barlow Condensed', 'Bahnschrift', 'Arial Narrow', 'Segoe UI', 'sans-serif'],
      },
      letterSpacing: {
        widest2: '0.2em',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        button: 'var(--shadow-button)',
      },
      borderRadius: {
        card: 'var(--radius-lg)',
        control: 'var(--radius-md)',
      },
    },
  },
  plugins: [],
};
